### ISSUE TITLE
tcd (chat download) now requires access_token specified 

### ISSUE THREAD

**Issue by trillex** [EnterGin/Auto-Stream-Recording-Twitch#15]
Chat download will always fail with `An error has occurred. VOD and chat will not be downloaded. Please check them manually.`

Running tcd manually gives a bit more information: 

```
PS C:\Scripts> tcd -v xxxxxxxx
Traceback (most recent call last):
  File "c:\users\trillex\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\trillex\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\trillex\AppData\Local\Programs\Python\Python38\Scripts\tcd.exe\__main__.py", line 7, in <module>
  File "c:\users\trillex\appdata\local\programs\python\python38\lib\site-packages\tcd\__init__.py", line 65, in main
    Arguments().oauth_token = requests.post(f"https://id.twitch.tv/oauth2/token"
KeyError: 'access_token'
```

This is due to the same changes I believe prompted the necessity to add the client_id and client_secret. 

Should be solved by parsing the self.client_id and self.client_secret to tcd's --client-id and --client-secret 

i.e. changing line 523, 525, 528 and 530 to include these: 

```
                         subprocess.Popen(['tcd', "--client-id", self.client_id, "--client-secret", self.client_secret, "-v", vod_id, "--timezone", self.timezoneName, "-f", "irc,ssa,json", "-o", processed_stream_path], stdout=None, stderr=None)
                                    else:
                                        subprocess.call(subtitles_window + ['tcd', "--client-id", self.client_id, "--client-secret", self.client_secret, "-v", vod_id, "--timezone", self.timezoneName, "-f", "irc,ssa,json", "-o", processed_stream_path])
                                else:
                                    if self.cmdstate == 2:
                                        subprocess.Popen(['tcd', "--client-id", self.client_id, "--client-secret", self.client_secret, "-v", vod_id, "--timezone", self.timezoneName, "-f", "irc,ssa,json", "-o", processed_stream_path], stdout=None, stderr=None)
                                    else:
                                        subprocess.call(' '.join(self.main_cmd_window + ['bash', '-c', "'tcd", "--client-id", self.client_id, "--client-secret", self.client_secret, "-v", vod_id, "--timezone", self.timezoneName, "-f", "irc,ssa,json", "-o", '"' + processed_stream_path + '"' + self.linuxstatecomma]), shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
```

Although this will sometimes not work, giving this error: 

```
Traceback (most recent call last):
  File "c:\users\trillex\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\trillex\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\trillex\AppData\Local\Programs\Python\Python38\Scripts\tcd.exe\__main__.py", line 7, in <module>
  File "c:\users\trillex\appdata\local\programs\python\python38\lib\site-packages\tcd\__init__.py", line 89, in main
    Downloader().videos(Arguments().video_ids)
  File "c:\users\trillex\appdata\local\programs\python\python38\lib\site-packages\tcd\downloader.py", line 181, in videos
    for video in self.helix_api.videos(video_ids):
  File "c:\users\trillex\appdata\local\programs\python\python38\lib\site-packages\twitch\helix\helix.py", line 51, in videos
    return helix.Videos(self.api, video_ids=video_ids, **kwargs)
  File "c:\users\trillex\appdata\local\programs\python\python38\lib\site-packages\twitch\helix\resources\videos.py", line 46, in __init__
    self._download_video_ids()
  File "c:\users\trillex\appdata\local\programs\python\python38\lib\site-packages\twitch\helix\resources\videos.py", line 125, in _download_video_ids
    videos: List[helix.Video] = self._next_videos_page(ignore_cache=True)
  File "c:\users\trillex\appdata\local\programs\python\python38\lib\site-packages\twitch\helix\resources\videos.py", line 84, in _next_videos_page
    response: dict = self._next_page(ignore_cache=ignore_cache)
  File "c:\users\trillex\appdata\local\programs\python\python38\lib\site-packages\twitch\helix\resources\resource.py", line 98, in _next_page
    response: dict = self._api.get(self._path, params=self._kwargs, ignore_cache=ignore_cache)
  File "c:\users\trillex\appdata\local\programs\python\python38\lib\site-packages\twitch\api.py", line 111, in get
    return self.request('GET', path, ignore_cache, params=params, headers=self._headers(headers), **kwargs)
  File "c:\users\trillex\appdata\local\programs\python\python38\lib\site-packages\twitch\api.py", line 100, in request
    response.raise_for_status()
  File "c:\users\trillex\appdata\local\programs\python\python38\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.twitch.tv/helix/videos?id=818095158
```

tcd most likely doesn't support helix just yet, although I don't know enough to come to any proper conclusion

**Comment by EnterGin** [comment]
Hello,
TCD moved to Helix a while ago. You can specify secret in tcd's config one time, not necessary to make it every time. But this arg would be useful.
TCD dev is great but I don't know why he didn't add try-except to prevent situations like this.

**Comment by trillex** [comment]
Good call on the config, it fills it out automatically after running it with --client_id and --client_secret the first time, pretty neat. (You can find the config location by running `tcd --settings` for other readers) 

But yeah, the API seems unreliable at best so it could be necessary for a loop to catch it or hope tcd will be "fixed"
