### ISSUE TITLE
cannot run code

### ISSUE THREAD

**Issue by Mango-Clark** [EnterGin/Auto-Stream-Recording-Twitch#35]
Traceback (most recent call last):
  File "C:\Auto_Recording_Twitch.py", line 1103, in <module>
    main(sys.argv[1:])
  File "C:\Auto_Recording_Twitch.py", line 1099, in main
    twitch_recorder.run()
  File "C:\Auto_Recording_Twitch.py", line 331, in run
    self.loopcheck()
  File "C:\Auto_Recording_Twitch.py", line 461, in loopcheck
    subprocess.call(["streamlink", '--http-header', 'Authorization=OAuth ' + self.oauth_tok_private,
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1491, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다

-----------------
python 3.11
Windows 10

**Comment by Mango-Clark** [comment]
ran code in powershell at file dirctory
> python ./Auto_Recording_Twitch.py
